export enum GlobalActions {
    LOGIN = 'LOGIN',
    LOGOUT = 'LOGOUT',
    UPDATE_THEME = 'UPDATE_THEME',
    UPDATE_SERVICE = 'UPDATE_SERVICE',
    UPDATE_SUMMARY = 'UPDATE_SUMMARY',
    CREATE_SERVICE = 'CREATE_SERVICE',
    REMOVE_SERVICE = 'REMOVE_SERVICE',
}
export default GlobalActions;