export enum GlobalActions {
    UPDATE_THEME = 'UPDATE_THEME',
    UPDATE_SERVICE = 'UPDATE_SERVICE',
    UPDATE_SUMMARY = 'UPDATE_SUMMARY',
    UPDATE_STARTTIME = 'UPDATE_STARTTIME',
    CREATE_SERVICE = 'CREATE_SERVICE',
    REMOVE_SERVICE = 'REMOVE_SERVICE',
}
export default GlobalActions;