export enum IEventType {
    //NO RESPONSE FROM API
    CODE_JUDY = 'CODE_JUDY',
    //ALL SUB SERVICES ARE DOWN
    CODE_GINA = 'CODE_GINA',
    //LESS THAN HALF SUB SERVICES ARE DOWN
    CODE_ROSA = 'CODE_ROSA',
    //MORE THAN HALF SUB SERVICES ARE DOWN
    CODE_JAKE = 'CODE_JAKE',
    //ALL SUB SERVICES ARE UP
    CODE_HOLT = 'CODE_HOLT',

    CODE_REST = 'CODE_REST'
}